### ISSUE TITLE
Add armadillo bindings

### ISSUE THREAD

**Issue by theAeon** [alugowski/fast_matrix_market#12]
Interested in using this library with armadillo. Should be a fairly simple task to bind to the MAT/SP_MAT/VEC types-let me know if you're willing to take a crack at it before I take a crack at it myself. Thanks!

**Comment by theAeon** [comment]
and for sparse:

```
fast_matrix_market::matrix_market_header headerA;
        std::ifstream ifsA(this->m_Afile_name);
        std::vector<UWORD> rowA;
        std::vector<UWORD> colA;
        std::vector<double> valueA;
        fast_matrix_market::read_matrix_market_triplet(ifsA, headerA, rowA, colA, valueA);
        arma::uvec urowa(rowA);
        arma::uvec ucola(colA);
        arma::umat ucoo = join_rows(urowa, ucola).t();
        arma::Col uvala(valueA);
        arma::spmat A(ucoo, uvala, headerA.nrows, headerA.ncols);
```

**Comment by alugowski** [comment]
That looks right. Does this serve your purposes?

The only way I can think of to improve is to write directly into the Mat instead of using an intermediate `std::vector`. That may require a fast_matrix_market improvement.

Writes should be doable with direct reads from both Mat and SpMat. As far as I can tell from a quick glance, SpMat has the standard CSC arrays so `csc_formatter` should take care of it.

**Comment by theAeon** [comment]
Yup-worked great for what i needed it to do. Might end up integrating it into more depending on how a meeting in the next few weeks goes.

Appreciate it!

**Comment by alugowski** [comment]
I added code to support any vector that supports resize() and begin(), not just `std::vector`. With that actual Armadillo bindings are somewhat trivial, so I went ahead and wrote them.

https://github.com/alugowski/fast_matrix_market/blob/main/README.Armadillo.md

They're already in main, I'll cut a release soon.

**Comment by theAeon** [comment]
> I looked into the Armadillo docs a bit more, and your dense matrix code has a subtle bug. Armadillo dense matrices are column-major (see https://arma.sourceforge.net/docs.html#Mat). FMM supports row or column, but this code:
> 
> > `fast_matrix_market::read_matrix_market_array(ifs, header, Bmem);`
> 
> uses the default of `row_major`.
> 
> So your matrices had their values transposed.

Well, that would explain why I had to throw in an extra transpose at the end of my initialization. Good catch,



> I added code to support any vector that supports resize() and begin(), not just `std::vector`. With that actual Armadillo bindings are somewhat trivial, so I went ahead and wrote them.
> 
> https://github.com/alugowski/fast_matrix_market/blob/main/README.Armadillo.md
> 
> They're already in main, I'll cut a release soon.

appreciate it!
