### ISSUE TITLE
add this to scipy?

### ISSUE THREAD

**Issue by ivirshup** [alugowski/fast_matrix_market#22]
Following up on:

* https://github.com/scverse/anndata/pull/962#issuecomment-1505161344

Could this library be included with scipy?

It's been a longstanding issue in SciPy that the matrix market readers are very slow. This library would meet scipy's standards for inclusion (C++ 11, header only), so I think this is a great opportunity to give great performance gains to a large audience. The scipy maintainers are, in principle, [open to this](https://discord.com/channels/786703927705862175/1020054666433802351/1095285619300765787).

On the side of this library, I think it would give potential users much more faith in the maintenance and continued support of this code. For users, it also means fewer python-level dependencies, and no need to worry about possible discrepancies between the parsers.

What do you think? (@eriknw, I would also be interested in hearing your thoughts here).

cc: @grst

**Comment by tupui** [comment]
Thank you for the proposal @ivirshup. I am linking the existing discussion on our mailing list.

https://mail.python.org/archives/list/scipy-dev@python.org/thread/43EJN2TMWFPEL6UD56KAIH6QYJQNC5TZ/#43EJN2TMWFPEL6UD56KAIH6QYJQNC5TZ

It looks like we "just" need the work to be done 😃

**Comment by ivirshup** [comment]
Great!

**Comment by eriknw** [comment]
This sounds great to me! `fast_matrix_market` works great for us in `python-graphblas`, and the few very minor differences compared to `scipy.io.mm{read,write}` that we found have been addressed.

**Comment by alugowski** [comment]
I just submitted a PR to scipy: https://github.com/scipy/scipy/pull/18631

**Comment by alugowski** [comment]
> I just submitted a PR to scipy: [scipy/scipy#18631](https://github.com/scipy/scipy/pull/18631)

Merged, so it appears FMM will be part of SciPy 1.12.
