### ISSUE TITLE
R bindings [WIP]

### ISSUE THREAD

**Issue by HaoZeke** [alugowski/fast_matrix_market#38]
I've started [maintaining a set of R bindings](https://haozeke.github.io/fastMatMR/) for this excellent library. There are some very nice [benchmarks compared](https://haozeke.github.io/fastMatMR/articles/fmm_write_bench.html) to the existing `Matrix` package in `R`. Perhaps a mention of this in the `readme` would be welcome? I'd be happy to open a PR.

The only thing left is support for reading from files.

**Comment by alugowski** [comment]
That's incredible! Yes absolutely make a PR.
