### ISSUE TITLE
QUERY: Giving credit

### ISSUE THREAD

**Issue by HaoZeke** [alugowski/fast_matrix_market#52]
Hi @alugowski, I was wondering if you'd be willing to be listed as a contributor in the [fastMatMR package](https://github.com/ropensci/fastMatMR). This is a standard practice in the `R` community (for [CRAN submissions](https://cran.r-project.org/), e.g. [here](https://github.com/cran/rlibkriging/blob/master/DESCRIPTION#L33-L35)) and I think it'd be really great to have you listed.

If it's ok, could you provide details in a comment with details like this?:

```
    person("Rohit", "Goswami", email = "rgoswami@ieee.org", role = c("ctb"),
           comment = c(ORCID = "0000-0002-2393-8056")),
```

The `ORCID` is optional, basically name and preferred email minimally :)

**Comment by alugowski** [comment]
Sure!

I'm not sure what the `role` field options are, so I'll let you enter whatever value you feel is appropriate.

```
person("Adam", "Lugowski", email = "alugowski@gmail.com", role = c("ctb"),
           comment = c(ORCID = "0009-0004-0922-4067")),
```

**Comment by HaoZeke** [comment]
Awesome, thanks :)

**Comment by HaoZeke** [comment]
Now [on CRAN](https://cran.r-project.org/web/packages/fastMatMR/index.html)!

![image](https://github.com/alugowski/fast_matrix_market/assets/4336207/e88624f8-641c-4f70-8f52-3ca636b6c7cd)

**Comment by alugowski** [comment]
That's awesome! Great work!

I skimmed through the review process thread, and thank you for all the time and effort you put into the project!
