### ISSUE TITLE
c++/9/thread:126: undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by chriszhao13** [alugowski/fast_matrix_market#54]
Hello! Adam. Thanks so much for the _[fast_matrix_market]_ project you created. 
I try to cmake the example. However, there is an issue showing  **_/9/thread:126: undefined reference to `pthread_create'_.**
I fix it by **_target_link_libraries(simple1 fast_matrix_market::fast_matrix_market pthread)_.**
Though, I think, the _pthread_ libraries should be linked by the [fast_matrix_market] market itself.
I want to verify it.

wishes!

**Comment by alugowski** [comment]
Interesting.

What version of compiler and OS are you running? What command printed that error?

FMM does not use pthreads, only native C++11 threads. These *may* be internally implemented using pthreads by some compilers, but do not require additional link arguments.

**Comment by alugowski** [comment]
@chriszhao13 I tried some additional platforms and compiler versions and was able to reproduce your issue. I believe your issue is fixed, would you mind retesting the latest `main` on your platform?

**Comment by alugowski** [comment]
Closed by #56
